### ISSUE TITLE
problem when test hilti 2022

### ISSUE THREAD

**Issue by iwander-all** [kekeliu-whu/Wildcat-SLAM#2]
Thanks for ur generous opensource. When I test exp07_long_corridor.bag in hilti 2022 dataset on [https://hilti-challenge.com/dataset-2022.html],  I find that it runs very slow and cannot catch up with the play of rosbag. And even worse that the result on rviz do not move, could you kindly offer a help for it ?

**Comment by kekeliu-whu** [comment]
The exp07_long_corridor.bag contains data from a degenerate scenario, and it may be difficult for this demo version of the program to achieve good results. This is my result of the exp07 sequence, and upon zooming in, the misalignment of the point clouds can be observed.
![Screenshot from 2024-03-27 21-47-19](https://github.com/flex-transformer/Wildcat-SLAM/assets/19950321/dad511df-f93f-4fb1-98ef-a169fc2d8c78)

Moreover, this program has not been optimized for performance, resulting in bad runtime performance. It is recommended to use the following launch file for debugging:

```
<launch>

  <node pkg="wildcat_slam" type="wildcat_slam_node" name="wildcat_slam_node" output="screen" args="--log_dir=/tmp --enable_online_mode=offline --bag_filename=$(arg bag_filename)" />

  <arg name="rviz" default="true" />
  <group if="$(arg rviz)">
      <node launch-prefix="nice" pkg="rviz" type="rviz" name="rviz" args="-d $(find wildcat_slam)/rviz/default.rviz" />
  </group>

</launch>
```

Ultimately, this program is far from complete, and the results are for reference only.
