### ISSUE TITLE
about pose predict function

### ISSUE THREAD

**Issue by whw-create** [kekeliu-whu/Wildcat-SLAM#3]
Thank you for your work first, I m curious that `PredictPoseOfNewImuState` function in lidar_odometry.cpp. `  i3.pos    = (i1.rot * (i1.acc - ba) + grav) * dt * dt + 2 * i2.pos - i1.pos;` why did you predict position in such a way? looking forward for your reply.

**Comment by kekeliu-whu** [comment]
The main consideration for this implementation is to closely follow the description in the paper as seen in Equation 13. The paper only uses translation and rotation to represent the trajectory, with the velocity information being implicitly contained in the differential of translation. The advantage of this approach is that the magnitude of the optimization variables is reduced to 2/3 of the original, making it more efficient to perform optimization. However, the downside is that the predicted translation is not accurate enough. This disadvantage might be mitigated by continuous sliding window optimization.
